name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download XC8
        shell: pwsh
        run: Invoke-WebRequest -Uri https://www.microchip.com/content/dam/mchp/documents/DEV/ProductDocuments/SoftwareTools/xc8-v2.32-full-install-windows-x64-installer.exe -OutFile xc8_install.exe

      - name: info
        run: ./xc8_install.exe --help

      - name: Install
        run: ./xc8_install.exe --mode "unattended" --LicenseType FreeMode --"Add to PATH" 0 ---prefix "C:\pic" --netservername "127.0.0.1"

      - name: Dir
        run: pwd && dir C:\pic\pic\ && dir C:\pic\pic\bin

      - name: Test make
        run: make --help

      - name: Add to Path
        run: echo "C:\pic\pic\bin" >> $GITHUB_ENV

      - name: Path
        run: $Env:Path

      - name: Test install
        run: xc8

